import getMainLayout from '@/utils/get-main-layout';
import { Box, Button, SxProps, Typography } from '@mui/material';
import Head from 'next/head';
import Image from 'next/image';
import { CSSProperties } from 'react';

Home.getLayout = (page: any) => getMainLayout(page);

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={styles.landingPageWrapper}>
          <Box sx={styles.firstHalfBox}>
            <Box sx={styles.mascotImageWrapper}>
              <Image
                alt="Chills Mascot"
                src="/logo-v0.webp"
                fill
                style={styles.mascotImage as CSSProperties}
                loading="eager"
              />
            </Box>
          </Box>
          <Box sx={styles.secondHalfBox}>
            <Box sx={{ maxWidth: 500, paddingBottom: 3 }}>
              <Typography
                component="h1"
                variant="h4"
                fontFamily="Nunito"
                sx={styles.title}
              >
                Embrace a new journey
              </Typography>
              <Typography
                component="p"
                variant="h6"
                fontFamily="Nunito"
                sx={styles.description}
              >
                A friendly, fun, active, and very accepting community, where you
                can meet people of all kind, and that is highly shaped by
                feedback of its members. This community is ours, and we decide
                its future together.
              </Typography>
              <Box
                sx={{
                  display: 'flex',
                  mt: 3,
                  gap: 1.5,
                  justifyContent: 'center',
                }}
              >
                <Button variant="contained" sx={styles.loginButton}>
                  Login
                </Button>
                <Button variant="outlined" sx={styles.registerButton}>
                  Register
                </Button>
              </Box>
            </Box>
          </Box>
        </Box>
      </main>
    </>
  );
}

const styles: { [key: string]: SxProps } = {
  landingPageWrapper: {
    display: 'flex',
    minHeight: 'calc(100vh - 3.5rem)',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
  },
  firstHalfBox: {
    height: 'calc(50vh - 3.5rem)', // 3.5rem from navbar height
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: 1400,
  },
  secondHalfBox: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'column',
    maxWidth: 1400,
    //flex: 1,
    //height: 'calc(50vh)',
  },
  mascotImageWrapper: {
    position: 'relative',
    height: 'calc(50vh - 3.5rem - 24px - 24px)', // 3.5 rem from navbar height, 24px to add padding on top and bottom
    aspectRatio: '835/1781',
  },
  mascotImage: {
    position: 'absolute',
  },
  title: {
    textAlign: 'center',
    mb: 3,
    color: 'primary.main',
    fontWeight: 'bold',
    px: 4,
  },
  description: { textAlign: 'justify', px: 4 },
  loginButton: { fontSize: '1.25rem', width: '9rem', fontWeight: 'bold' },
  registerButton: {
    fontSize: '1.25rem',
    width: '9rem',
    borderWidth: '2px!important',
    borderColor: 'primary.main',
  },
};
